package com.adatechschool.beequizz.dataProvider.themes.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "tb_themes", schema = "quizz")
public class ThemeModel {
    @Id
    //Primary key values will be generated by the database itself
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_theme")
    private Integer idTheme;
    @Column(name = "name_theme")
    private String nameTheme;

    public ThemeModel() {
    }

    public Integer getIdTheme() {
        return idTheme;
    }

    public void setIdTheme(Integer idTheme) {
        this.idTheme = idTheme;
    }

    public String getNameTheme() {
        return nameTheme;
    }

    public void setNameTheme(String nameTheme) {
        this.nameTheme = nameTheme;
    }
}
