package com.adatechschool.beequizz.dataProvider.model;

import jakarta.persistence.*;

@Entity
@Table(name = "tb_answers", schema = "quizz")
public class AnswerModel {
    @Id
    //Primary key values will be generated by the database itself
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long idAnswer;

}
