package com.adatechschool.beequizz.model;

import jakarta.persistence.*;

@Entity
@Table(name="TB_Questions")
public class Question {
    @Id
    //Primary key values will be generated by the database itself
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String textQuestion;
    private Integer difficultyQuestion;

    //Constructors, Getters and Setters
    public void setId(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setTextQuestion(String textQuestion){
        this.textQuestion = textQuestion;
    }

    public String getTextQuestion(){
        return textQuestion;
    }

    public void setDifficultyQuestion(Integer difficultyQuestion){
        this.difficultyQuestion = difficultyQuestion;
    }

    public Integer getDifficultyQuestion() {
        return difficultyQuestion;
    }
}
