package com.adatechschool.beequizz.model;

import jakarta.persistence.*;

@Entity
@Table(name = "tb_questions", schema = "quizz")
public class QuestionModel {
    @Id
    //Primary key values will be generated by the database itself
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long idQuestion;
    private String textQuestion;
    private Integer difficultyQuestion;

    public Long getIdQuestion() {
        return idQuestion;
    }

    //Constructors, Getters and Setters
    public void setIdQuestion(Long id) {
        this.idQuestion = id;
    }

    public String getTextQuestion() {
        return textQuestion;
    }

    public void setTextQuestion(String textQuestion) {
        this.textQuestion = textQuestion;
    }

    public Integer getDifficultyQuestion() {
        return difficultyQuestion;
    }

    public void setDifficultyQuestion(Integer difficultyQuestion) {
        this.difficultyQuestion = difficultyQuestion;
    }
}
