package com.adatechschool.beequizz.dataProvider.question.entity;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import jakarta.persistence.*;

import java.util.List;

// This model is also an entity which means that it is also used for persistent data stored in the database.
@Entity
@Table(name = "tb_questions", schema = "quizz")
public class QuestionModel {
    @Id
    //Primary key values will be generated by the database itself
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long idQuestion;
    private String textQuestion;
    private Integer difficultyQuestion;
    @OneToMany(mappedBy = "question", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonManagedReference
    private List<AnswerModel> answers;

    public QuestionModel() {
    }

    public Long getIdQuestion() {
        return idQuestion;
    }

    public void setIdQuestion(Long idQuestion) {
        this.idQuestion = idQuestion;
    }

    public String getTextQuestion() {
        return textQuestion;
    }

    public void setTextQuestion(String textQuestion) {
        this.textQuestion = textQuestion;
    }

    public Integer getDifficultyQuestion() {
        return difficultyQuestion;
    }

    public void setDifficultyQuestion(Integer difficultyQuestion) {
        this.difficultyQuestion = difficultyQuestion;
    }

    public List<AnswerModel> getAnswers() {
        return answers;
    }

    public void setAnswers(List<AnswerModel> answers) {
        this.answers = answers;
    }
}
